
import { GoogleGenAI } from "@google/genai";
import { ThumbnailConfig } from "../types";

export const generateThumbnail = async (config: ThumbnailConfig): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const adjustmentInstructions = `
    IMAGE ADJUSTMENTS:
    - Brightness: ${config.adjustments.brightness}%
    - Contrast: ${config.adjustments.contrast}%
    - Saturation: ${config.adjustments.saturation}%
    - Hue Rotation: ${config.adjustments.hue}deg
    - Blur Intensity: ${config.adjustments.blur}px (apply to background mainly)
    - Temperature: ${config.adjustments.temperature > 0 ? 'Warm' : 'Cool'}
    - Color Inversion: ${config.adjustments.invert ? 'Yes' : 'No'}
    - Grayscale: ${config.adjustments.grayscale}%
  `;

  const colorInstructions = config.usePrimaryColor 
    ? `COLOR BRANDING: Use ${config.primaryColor} as the dominant accent color for text, glows, and key visual elements.`
    : `COLOR BRANDING: Use a color palette that best fits the "${config.tone}" mood automatically.`;

  let prompt = `
    Create a professional YouTube Thumbnail.
    Canvas Size: 1280x720 (16:9 aspect ratio).
    
    TEXT INSTRUCTIONS:
    - Text: "${config.text.toUpperCase()}"
    - Font Style: Bold, Sans-serif (Anton or Bebas Neue style).
    - Positioning: Large, high contrast, positioned for maximum impact.
    - Effects: Strong outline and drop shadow to pop against background.
    
    SUBJECT INSTRUCTIONS:
    - Main Subject: ${config.subjectDescription}
    - Style: Sharp focus, high clarity, clean edges (cut-out style).
    - Effects: Add a subtle glow or rim light around the subject to separate from background.
    
    COMPOSITION:
    - Layout: Keep 1 main focal point using rule of thirds.
    - Mood: ${config.tone}.
    - Background: Simple, blurred or gradient background to avoid clutter.
    - Style: Professional, clean, and optimized for mobile screens.
    
    ${colorInstructions}
    ${adjustmentInstructions}
  `;

  if (config.referenceImage) {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: config.referenceImage.split(',')[1],
              mimeType: 'image/png',
            },
          },
          {
            text: `Recreate this thumbnail layout exactly. Keep the same composition and visual hierarchy. 
            However, REPLACE the existing text with "${config.text.toUpperCase()}" 
            and REPLACE the main subject with: ${config.subjectDescription}. 
            Apply a high-contrast ${config.tone} mood.
            ${colorInstructions}
            ${adjustmentInstructions}
            Ensure the text is extremely readable for mobile users.`
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the model.");
  } else {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the model.");
  }
};
