
import { GoogleGenAI } from "@google/genai";
import { ThumbnailConfig } from "../types";

export const generateThumbnail = async (config: ThumbnailConfig): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  // Base prompt instructions focusing on high CTR and specific structure
  let prompt = `
    Create a professional YouTube Thumbnail.
    Canvas Size: 1280x720 (16:9 aspect ratio).
    
    TEXT INSTRUCTIONS:
    - Text: "${config.text.toUpperCase()}"
    - Font Style: Bold, Sans-serif (Anton or Bebas Neue style).
    - Positioning: Large, high contrast, positioned for maximum impact.
    - Effects: Strong outline and drop shadow to pop against background.
    
    SUBJECT INSTRUCTIONS:
    - Main Subject: ${config.subjectDescription}
    - Style: Sharp focus, high clarity, clean edges (cut-out style).
    - Effects: Add a subtle glow or rim light around the subject to separate from background.
    
    COMPOSITION & COLORS:
    - Layout: Keep 1 main focal point using rule of thirds.
    - Colors: Use dominant colors ${config.primaryColor} and ${config.secondaryColor}.
    - Mood: ${config.tone}.
    - Background: Simple, blurred or gradient background to avoid clutter.
    - Style: Professional, clean, and optimized for mobile screens (high readability at small size).
  `;

  if (config.referenceImage) {
    // IMAGE EDITING / RECREATION MODE
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: config.referenceImage.split(',')[1],
              mimeType: 'image/png',
            },
          },
          {
            text: `Recreate this thumbnail layout exactly. Keep the same composition and visual hierarchy. 
            However, REPLACE the existing text with "${config.text.toUpperCase()}" 
            and REPLACE the main subject with: ${config.subjectDescription}. 
            Apply a high-contrast ${config.tone} mood using ${config.primaryColor} colors. 
            Ensure the text is extremely readable for mobile users.`
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the model.");
  } else {
    // TEXT-TO-IMAGE MODE
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the model.");
  }
};
